export enum ReportReason {
	BEHAVIOR = "BEHAVIOR",
	SCAM = "SCAM",
	HARASSMENT = "HARASSMENT",
	SAFETY = "SAFETY",
	GUIDELINES = "GUIDELINES",
	MISREPRESENTATION = "MISREPRESENTATION",
	OFF_TOPIC = "OFF_TOPIC",
	OTHER = "OTHER",
}
